name: meuua
description: A dashboard for meuua

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.2
  retrofit: 3.0.1+1
  json_annotation: 4.5.0
  dio: 4.0.6
  shared_preferences: ^2.0.15
  adaptive_breakpoints: ^0.1.4
  adaptive_components: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  retrofit_generator: 4.0.1
  build_runner: 2.1.11
  json_serializable: 6.2.0
  model_generator: 5.8.1

flutter:
  uses-material-design: true

model_generator:
  retrofit_compute: true
  to_string: true